"""Add_Pages

Revision ID: 02440013c8e0
Revises: be7d8e43fb32
Create Date: 2023-02-07 18:21:07.143325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02440013c8e0'
down_revision = 'be7d8e43fb32'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('pages', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'pages')
    # ### end Alembic commands ###
